import { Complex, Scalar } from '../src/complex';
import { Polynomial } from '../src/polynomial';

// Generated by CodiumAI

describe('Polynomial', () => {

    // Creating a Polynomial from an array of coefficients
    it('should create a Polynomial from an array of coefficients', () => {
        const coefficients: [number, Scalar][] = [[0, 1], [1, 2], [2, 3]];
        const polynomial = Polynomial.fromArray(coefficients);
        expect(polynomial.toString()).toBe('(3 + 0i)x^2 + (2 + 0i)x + (1 + 0i)');
    });

    // Creating a Polynomial from a map of coefficients
    it('should create a Polynomial from a map of coefficients', () => {
        const coefficients = new Map([[0, 1], [1, 2], [2, 3]]);
        const polynomial = Polynomial.fromMap(coefficients);
        expect(polynomial.toString()).toBe('(3 + 0i)x^2 + (2 + 0i)x + (1 + 0i)');
    });

    // Adding two Polynomials
    it('should add two Polynomials correctly', () => {
        const poly1 = Polynomial.fromArray([[0, 1], [1, 2]]);
        const poly2 = Polynomial.fromArray([[0, 3], [1, 4]]);
        const result = poly1.add(poly2);
        expect(result.toString()).toBe('(6 + 0i)x + (4 + 0i)');
    });

    // Subtracting one Polynomial from another
    it('should subtract one Polynomial from another correctly', () => {
        const poly1 = Polynomial.fromArray([[0, 5], [1, 7]]);
        const poly2 = Polynomial.fromArray([[0, 3], [1, 4]]);
        const result = poly1.subtract(poly2);
        expect(result.toString()).toBe('(3 + 0i)x + (2 + 0i)');
    });

    // Multiplying two Polynomials
    it('should multiply two Polynomials correctly', () => {
        const poly1 = Polynomial.fromArray([[0, 1], [1, 2]]);
        const poly2 = Polynomial.fromArray([[0, 3], [1, 4]]);
        const result = poly1.multiply(poly2);
        expect(result.toString()).toBe("(8 + 0i)x^2 + (10 + 0i)x + (3 + 0i)");
    });

    // Dividing one Polynomial by another
    it('should divide one Polynomial by another correctly', () => {
        const poly1 = Polynomial.fromArray([[2, 1]]);
        const poly2 = Polynomial.fromArray([[1, 1]]);
        const result = poly1.divide(poly2);
        expect(result.toString()).toBe('(1 + 0i)x');
    });

    // Dividing two Polynomials with different degrees
    it('should divide two Polynomials with different degrees when invoked', () => {
        const poly1 = Polynomial.fromArray([[0, 1], [1, 1], [2, 1]]);
        const poly2 = Polynomial.fromArray([[0, 1], [1, 2]]);
        const result = poly1.divide(poly2, false);
        expect(result.toString()).toBe('(0.5 + 0i)x + (0.25 + 0i)');
    });

    // Creating a Polynomial with all zero coefficients
    it('should create a zero Polynomial when all coefficients are zero', () => {
        const coefficients: [number, Scalar][] = [[0, 0], [1, 0], [2, 0]];
        const polynomial = Polynomial.fromArray(coefficients);
        expect(polynomial.isZero()).toBe(true);
        expect(polynomial.toString()).toBe('0');
    });

    // Adding a zero Polynomial to another Polynomial
    it('should return the same Polynomial when adding a zero Polynomial', () => {
        const poly1 = Polynomial.fromArray([[0, 1], [1, 2]]);
        const zeroPoly = Polynomial.fromArray([[0, 0]]);
        const result = poly1.add(zeroPoly);
        expect(result.toString()).toBe('(2 + 0i)x + (1 + 0i)');
    });

    // Subtracting a zero Polynomial from another Polynomial
    it('should return the same Polynomial when subtracting a zero Polynomial', () => {
        const poly1 = Polynomial.fromArray([[0, 1], [1, 2]]);
        const zeroPoly = Polynomial.fromArray([[0, 0]]);
        const result = poly1.subtract(zeroPoly);
        expect(result.toString()).toBe('(2 + 0i)x + (1 + 0i)');
    });

    // Multiplying a Polynomial by a zero Polynomial
    it('should return a zero Polynomial when multiplying by a zero Polynomial', () => {
        const poly1 = Polynomial.fromArray([[0, 1], [1, 2]]);
        const zeroPoly = Polynomial.fromArray([[0, 0]]);
        const result = poly1.multiply(zeroPoly);
        expect(result.isZero()).toBe(true);
        expect(result.toString()).toBe('0');
    });

    // Dividing a Polynomial by a zero Polynomial (should throw an error)
    it('should throw an error when dividing by a zero Polynomial', () => {
        const poly1 = Polynomial.fromArray([[0, 1], [1, 2]]);
        const zeroPoly = Polynomial.fromArray([[0, 0]]);
        expect(() => poly1.divide(zeroPoly)).toThrow('Division by zero');
    });

    // Substituting zero into a Polynomial
    it('should return the constant term when substituting zero into a Polynomial', () => {
        const poly = Polynomial.fromArray([[0, 5], [1, 7]]);
        const result = poly.substitute(Complex.zero);
        expect(result.equals(Complex.fromCartesian(5, 0))).toBe(true);
    });

    // Substituting a value into a Polynomial
    it('should substitute a value into a Polynomial when using Cartesian form', () => {
        const coefficients: [number, Scalar][] = [[0, 1], [1, 2], [2, 3]];
        const polynomial = Polynomial.fromArray(coefficients);
        const value = 2;
        const result = polynomial.substitute(value, false);
        expect(result.toString()).toBe('17 + 0i');
    });

    // Calculating the degree of a Polynomial
    it('should calculate the degree of a Polynomial when having multiple terms', () => {
        const coefficients: [number, Scalar][] = [[0, 1], [1, 2], [2, 3]];
        const polynomial = Polynomial.fromArray(coefficients);
        expect(polynomial.degree()).toBe(2);
    });
});
